AnotherStarbucksOrder/another_back

src/main/java/com/starbucksorder/another_back/controller/MenuController.java
src/main/java/com/starbucksorder/another_back/dto/admin/MenuDto.java
src/main/java/com/starbucksorder/another_back/entity/Menu.java
src/main/java/com/starbucksorder/another_back/repository/MenuMapper.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/resources/mappers/menu.xml

FEATURE 관리자메뉴 페이지네이션 기능 추가

---

src/main/java/com/starbucksorder/another_back/dto/admin/MenuDto.java
src/main/java/com/starbucksorder/another_back/entity/Menu.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/resources/mappers/menu.xml

UPDATE 관리자 메뉴관리 메뉴 조회

---

src/main/java/com/starbucksorder/another_back/entity/OptionDetail.java

private String -> int optionDetailPrice 변경
결휘

UPDATE ENTITY - OptionDetail

---

src/main/java/com/starbucksorder/another_back/service/PointService.java

REFACTOR PointService

---

pom.xml
src/main/java/com/starbucksorder/another_back/controller/MenuController.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/MenuDetailRespDto.java
src/main/java/com/starbucksorder/another_back/entity/Menu.java
src/main/java/com/starbucksorder/another_back/repository/MenuDetailMapper.java
src/main/java/com/starbucksorder/another_back/repository/MenuMapper.java
src/main/java/com/starbucksorder/another_back/security/jwt/JwtProvider.java
src/main/java/com/starbucksorder/another_back/security/jwt/package-info.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/resources/mappers/menu.xml

메뉴 상세보기 조회기능 구현
UPDATE JWT토큰 유효기한 수정
결휘

FEATURE 메뉴관리 상세보기

---

src/main/java/com/starbucksorder/another_back/controller/MenuController.java
src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderDto.java
src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderPortOneDto.java

HACK: portone 도입 전 데이터 형식 확인
결휘

TEST Order

---

src/main/java/com/starbucksorder/another_back/controller/MenuController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/menu/ReqAdminModifyDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/menu/RespAdminMenuList.java
src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderPortOneDto.java
src/main/java/com/starbucksorder/another_back/repository/CategoryMapper.java
src/main/java/com/starbucksorder/another_back/repository/MenuDetailMapper.java
src/main/java/com/starbucksorder/another_back/repository/MenuMapper.java
src/main/java/com/starbucksorder/another_back/security/handler/AuthenticationHandler.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/resources/mappers/category.xml
src/main/resources/mappers/menu.xml
src/main/resources/mappers/menu_detail.xml

UPDATE 토큰유효성 에러코드403 -> 401 변경
결휘

FEATURE 메뉴관리_메뉴수정

---

src/main/java/com/starbucksorder/another_back/dto/admin/response/menu/MenuAdminDetailRespDto.java
src/main/java/com/starbucksorder/another_back/entity/Menu.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java

내부클래스 MenuAdminDetailRespDto 분리
결휘

UPDATE Response요소 추가

---

src/main/java/com/starbucksorder/another_back/controller/OptionController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/option/ReqAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/option/RespAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/entity/Option.java
src/main/java/com/starbucksorder/another_back/entity/OptionDetail.java
src/main/java/com/starbucksorder/another_back/repository/OptionMapper.java
src/main/java/com/starbucksorder/another_back/service/DuplicateService.java
src/main/java/com/starbucksorder/another_back/service/OptionService.java
src/main/resources/mappers/option.xml

FEATURE 관리자카테고리, 옵션

---

src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderPortOneDto.java
src/main/resources/mappers/user.xml

UPDATE 사용자 포인트조회

---

src/main/java/com/starbucksorder/another_back/entity/OptionDetail.java
src/main/resources/mappers/menu.xml

UPDATE 사용자 메뉴 상세보기

---

src/main/java/com/starbucksorder/another_back/dto/user/response/point/RespUserDto.java
src/main/resources/mappers/user.xml

UPDATE 사용자조회요청 수정

---

src/main/java/com/starbucksorder/another_back/controller/CategoryController.java
src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/category/RespAdminCategoryDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/option/RespAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/entity/Category.java
src/main/java/com/starbucksorder/another_back/entity/MenuDetail.java
src/main/java/com/starbucksorder/another_back/entity/Option.java
src/main/java/com/starbucksorder/another_back/repository/MenuCategoryMapper.java
src/main/java/com/starbucksorder/another_back/service/CategoryService.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/java/com/starbucksorder/another_back/service/PointService.java
src/main/resources/mappers/menu.xml
src/main/resources/mappers/menu_category.xml
src/main/resources/mappers/option.xml

FIX 메뉴상세보기

---

pom.xml
src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderDto.java
src/main/java/com/starbucksorder/another_back/repository/OrderDetailMapper.java
src/main/java/com/starbucksorder/another_back/repository/UserMapper.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/resources/mappers/order.xml
src/main/resources/mappers/order_detail.xml
src/main/resources/mappers/user.xml

FEATURE 결제요청

---

pom.xml
src/main/java/com/starbucksorder/another_back/config/SwaggerConfig.java
src/main/resources/application.yml

FEATURE 스웨거도입

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderDto.java
src/main/java/com/starbucksorder/another_back/dto/user/response/point/RespUserDto.java
src/main/java/com/starbucksorder/another_back/entity/User.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/java/com/starbucksorder/another_back/service/PointService.java
src/main/resources/mappers/user.xml

FEATURE 사용자 포인트 사용 조회 요청

---

src/main/java/com/starbucksorder/another_back/controller/AuthController.java
src/main/java/com/starbucksorder/another_back/controller/OptionController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/option/ReqAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/option/ReqAdminOptionsDto.java
src/main/java/com/starbucksorder/another_back/entity/Option.java
src/main/java/com/starbucksorder/another_back/service/OptionService.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/resources/mappers/option.xml

UPDATE 옵션에 속한 메뉴들 전체 불러오기

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java

UPDATE 사용자 결제요청

---

src/main/java/com/starbucksorder/another_back/controller/OptionController.java
src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/option/ReqAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/repository/OptionMapper.java
src/main/java/com/starbucksorder/another_back/service/OptionService.java
src/main/resources/mappers/option.xml

FEATURE 관리자 옵션기능

---

src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/ReqAdminUserDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/option/ReqAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/user/RespAdminDto.java
src/main/java/com/starbucksorder/another_back/entity/OptionDetail.java
src/main/java/com/starbucksorder/another_back/entity/User.java
src/main/java/com/starbucksorder/another_back/repository/UserMapper.java
src/main/java/com/starbucksorder/another_back/service/OptionService.java
src/main/java/com/starbucksorder/another_back/service/UserService.java
src/main/resources/mappers/option.xml
src/main/resources/mappers/user.xml

UPDATE 관리자 옵션

---

src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/service/CategoryService.java
src/main/resources/mappers/menu_category.xml

불러올 때 메뉴들이 널 값인 경우 빈 배열로 처리
결휘

UPDATE 관리자 카테고리 관리

---

src/main/java/com/starbucksorder/another_back/dto/admin/request/user/ReqAdminDeleteDto.java

FEATURE 관리자 회원관리 기능

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderItem.java
src/main/java/com/starbucksorder/another_back/dto/user/response/menu/RespMenuImgListDto.java
src/main/java/com/starbucksorder/another_back/entity/Menu.java
src/main/java/com/starbucksorder/another_back/repository/MenuMapper.java
src/main/java/com/starbucksorder/another_back/repository/UserMapper.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/resources/mappers/menu.xml

TEST 쿠폰 불러오기

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/user/RespAdminDto.java
src/main/java/com/starbucksorder/another_back/entity/User.java
src/main/java/com/starbucksorder/another_back/repository/MenuMapper.java

UPDATE 사용자 쿠폰 관련

---

src/main/java/com/starbucksorder/another_back/dto/user/request/Order/ReqOrderDto.java
src/main/java/com/starbucksorder/another_back/repository/CouponMapper.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/resources/mappers/coupon.xml

FEATURE 사용자 쿠폰 사용

---

src/main/java/com/starbucksorder/another_back/service/PointService.java
src/main/resources/mappers/user.xml

사용가능한 쿠폰이 없는 경우 null로 예외처리 인식 로직 수정
결휘

UPDATE 쿠폰 사용

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/order/RespOrderDetailDto.java
src/main/java/com/starbucksorder/another_back/entity/Order.java
src/main/java/com/starbucksorder/another_back/entity/OrderDetail.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/resources/mappers/order.xml

FEATURE 관리자 주문관리

---

src/main/java/com/starbucksorder/another_back/dto/admin/request/order/ReqAdminOrderDto.java

UPDATE 관리자 주문관리

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/controller/SalesController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/ReqAdminPageDateDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/order/ReqAdminOrderDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/CMRespAdminDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/Sales/RespSaleDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/order/RespOrderListDto.java
src/main/java/com/starbucksorder/another_back/repository/OrderMapper.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/java/com/starbucksorder/another_back/service/SalesService.java
src/main/java/com/starbucksorder/another_back/service/UserService.java
src/main/resources/mappers/order.xml

매출 대시보드 조회
주문관리 날짜 조회 로직 수정
결휘

FEATURE 관리자 매출,주문관리

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/controller/SalesController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/order/ReqAdminOrderDto.java
src/main/java/com/starbucksorder/another_back/repository/OrderMapper.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/java/com/starbucksorder/another_back/service/SalesService.java
src/main/resources/mappers/order.xml

UPDATE 관리자 주문 조회

---

src/main/java/com/starbucksorder/another_back/controller/SalesController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/order/ReqAdminOrderDto.java
src/main/java/com/starbucksorder/another_back/repository/OrderMapper.java
src/main/java/com/starbucksorder/another_back/service/SalesService.java
src/main/resources/mappers/order.xml

FEATURE 관리자매출관리

---

src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/repository/OrderMapper.java
src/main/java/com/starbucksorder/another_back/service/OrderService.java
src/main/resources/mappers/order.xml

UPDATE 관리자 주문취소

---

src/main/java/com/starbucksorder/another_back/controller/SalesController.java
src/main/java/com/starbucksorder/another_back/repository/OrderMapper.java
src/main/java/com/starbucksorder/another_back/service/SalesService.java
src/main/resources/mappers/order.xml

UPDATE 관리자 매출관리

---

src/main/java/com/starbucksorder/another_back/service/SalesService.java
src/main/resources/mappers/order.xml

UPDATE 관리자 매출 대시보드

---

src/main/java/com/starbucksorder/another_back/controller/AuthController.java
src/main/java/com/starbucksorder/another_back/controller/CategoryController.java
src/main/java/com/starbucksorder/another_back/controller/ExceptionControllerAdvice.java
src/main/java/com/starbucksorder/another_back/controller/MenuController.java
src/main/java/com/starbucksorder/another_back/controller/OptionController.java
src/main/java/com/starbucksorder/another_back/controller/OrderController.java
src/main/java/com/starbucksorder/another_back/controller/SalesController.java
src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/repository/MenuMapper.java
src/main/java/com/starbucksorder/another_back/repository/UserMapper.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/java/com/starbucksorder/another_back/service/UserService.java
src/main/resources/mappers/menu.xml
src/main/resources/mappers/user.xml

REFACTOR ApiOperation

---

src/main/java/com/starbucksorder/another_back/aspect/ValidAspect.java
src/main/java/com/starbucksorder/another_back/controller/AuthController.java
src/main/java/com/starbucksorder/another_back/controller/CategoryController.java
src/main/java/com/starbucksorder/another_back/controller/ExceptionControllerAdvice.java
src/main/java/com/starbucksorder/another_back/controller/MenuController.java
src/main/java/com/starbucksorder/another_back/controller/OptionController.java
src/main/java/com/starbucksorder/another_back/controller/UserController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/ReqAdminUserDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/category/ReqAdminCategoryDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/menu/ReqAdminModifyDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/option/ReqAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/entity/OptionDetail.java
src/main/java/com/starbucksorder/another_back/exception/ValidException.java

등록 수정에 대한 유효성 검사
메뉴, 카테고리, 옵션, 회원
유효성검사 오류에대한 응답 값 변경
결휘

REFACOTR 등록,수정

---

src/main/java/com/starbucksorder/another_back/dto/admin/request/menu/ReqAdminDto.java

REFACTOR 유효성검사

---

src/main/java/com/starbucksorder/another_back/controller/SalesController.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/ReqAdminSalePageDateDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/request/menu/ReqAdminDto.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/Sales/RespAdminSaleListDto.java
src/main/resources/mappers/order.xml

REFACTOR 매출관리

---

src/main/java/com/starbucksorder/another_back/controller/CategoryController.java
src/main/java/com/starbucksorder/another_back/dto/admin/response/option/RespAdminOptionDto.java
src/main/java/com/starbucksorder/another_back/entity/Option.java
src/main/java/com/starbucksorder/another_back/repository/OptionMapper.java
src/main/java/com/starbucksorder/another_back/service/MenuService.java
src/main/java/com/starbucksorder/another_back/service/OptionService.java
src/main/resources/mappers/option.xml

UPDATE 관리자 옵션 관리

---

src/main/java/com/starbucksorder/another_back/service/PointService.java

UPDATE 사용자 조회

---

src/main/java/com/starbucksorder/another_back/controller/SalesController.java

MERGE main 취합
